[package]
name = "heavykeeper"
version = "0.2.4"
edition = "2021"

[lib]
name = "heavykeeper"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
heavykeeper = { version = "0.6.2" }

[package.metadata.maturin]
name = "heavykeeper"
